version: "3.8"

services:
  frontend:
    image: frontend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:3000
    # depends_on:
    #   - bdd
    restart: unless-stopped
