version: "3.8"

services:
  frontend:
    image: frontend:dev
    build:
      context: .
      dockerfile: Dockerfile_dev
    ports:
      - 80:3000
    volumes:
      - type: bind
        source: .
        target: /app/
      - type: volume
        target: /app/node_modules
    restart: unless-stopped
